/* Generated By:JavaCC: Do not edit this line. AutomataParserConstants.java */
package ricm3.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AutomataParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int UNARY = 7;
  /** RegularExpression Id. */
  int BINOP = 8;
  /** RegularExpression Id. */
  int DIRVAR = 9;
  /** RegularExpression Id. */
  int DIRECTION = 10;
  /** RegularExpression Id. */
  int ENTVAR = 11;
  /** RegularExpression Id. */
  int ENTITY = 12;
  /** RegularExpression Id. */
  int ID = 13;
  /** RegularExpression Id. */
  int INT = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<LETTER>",
    "<DIGIT>",
    "<UNARY>",
    "<BINOP>",
    "\"d\"",
    "<DIRECTION>",
    "\"e\"",
    "<ENTITY>",
    "<ID>",
    "<INT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"*\"",
    "\":\"",
    "\"_\"",
    "\"?\"",
    "\"|\"",
    "\",\"",
  };

}
